### ISSUE TITLE
Use Read The Docs for documentation

### ISSUE THREAD

**Issue by arnodelorme** [sccn/EEGDash#18]
```
pip install sphinx
sphinx-quickstart
```

- Modify index.rst and other .rst files inside the docs/ directory.
- Sign up for https://about.readthedocs.com/?ref=readthedocs.org
- Import the GitHub repo and Grant Read the Docs permission to access your repo
- Create a .readthedocs.yml file in your project’s root directory for build configuration

```
version: 2
formats: ["htmlzip", "pdf"]
sphinx:
  configuration: docs/conf.py
python:
  install:
    - requirements: docs/requirements.txt
```

- Access documentation at https://your-project.readthedocs.io/
- Under Domains in read the docs, add your custom domain (e.g., docs.yourdomain.com).
- Update Your Domain’s DNS Records and add a CNAME record pointing your domain (e.g., docs.yourdomain.com) to: readthedocs.io (If you are using a root domain (e.g., yourdomain.com), you may need to use an A record pointing to Read the Docs’ IP address).
- Enable HTTPS. Read the Docs automatically provides free HTTPS via Let’s Encrypt. You may need to wait for the SSL certificate to be issued.
